### ISSUE TITLE
[BUG] PMC Kills Number is also Assigned to the Counter Condition

### ISSUE THREAD

**Issue by MTeyCFA** [CathieNova/Haven-Tools-and-Helpers#14]
I'm really sorry, I don't know how to title this bug.

The quest I created features PMC killing other PMCs with Pistols and Headshots. I've told it to count 3 kills. 
![image](https://github.com/user-attachments/assets/f61e7916-6b9a-4aae-89c3-3e1c6610c7e1)

The bug I encountered was that it assigned the value 3 to both the value of enemies killed as well as each enemy as defined by the quest condition.

So, the website outputs this:
![image](https://github.com/user-attachments/assets/06827555-ba81-4209-969c-b4ee982eddc2)

The code generates the value 3 for both the condition of the "kill" as well as the number of kills. The code expects the PMC to get 3 Headshots at once to count 1 for the overall kills.

The solution was to change the value of the condition from 3 to 1.

```
....
"target": "AnyPmc",
"value": 1,
"weapon": []
....
```

![image](https://github.com/user-attachments/assets/9d212a0b-5fe3-49b5-aa47-c429cf69dd75)

I am not sure if this is just for the Kill condition or not, it might happened on each quest created that features a number higher than 1 for anything.

**Comment by CathieNova** [comment]
Fixed, should work in the next 3 mins
