### ISSUE TITLE
[BUG] Time restriction in 'kill' objective condition does not print to JSON

### ISSUE THREAD

**Issue by Gholdin** [CathieNova/Haven-Tools-and-Helpers#8]
**Description**
When adjusting the time variable "Time of day from" and "Time of day to" and then generating a JSON, the code output does not reflect the time adjustment.

**Steps to Reproduce**
1. Select 'kill' objective
3. Set time from/to whatever you want
4. Generate JSON

**Expected Behavior**
"from" and "to" variables should reflect exact numerical input using the JSON helper tool. 

**Actual Behavior**
Time was set from 22, and to 5. 'from' and 'to' variables in the daytime condition remain 0 on output.
`{
          "completeInSeconds": 0,
          "conditionType": "CounterCreator",
          "counter": {
            "conditions": [
              {
                "bodyPart": [],
                "compareMethod": ">=",
                "conditionType": "Kills",
                "daytime": {
                  "from": 0,
                  "to": 0
                },
                "distance": {
                  "compareMethod": ">=",
                  "value": 0
                },
                "dynamicLocale": false,
                "enemyEquipmentExclusive": [],
                "enemyEquipmentInclusive": [],
                "enemyHealthEffects": [],
                "id": "67399e35d2dd62a6e3554c52",
                "resetOnSessionEnd": false,
                "savageRole": [],
                "target": "Any",
                "value": 1,
                "weapon": [],
                "weaponCaliber": [],
                "weaponModsInclusive": [],
                "weaponModsExclusive": [],
                "equipmentInclusive": [],
                "equipmentExclusive": []
              }`

**Browser**
Chrome

**Comment by CathieNova** [comment]
I can't fix that issue as i'm in the middle of a HUGE overhaul on the page.
I will fix it as soon as i'm done with the overhaul (hopefully tomorrow)

**Comment by CathieNova** [comment]
daytime is now fixed for both Objective Condition and Fail Condition

**Comment by Gholdin** [comment]
Thanks! Just checked and it worked
