### ISSUE TITLE
[BUG] Subsequent "SAVAGE ROLE" option not given on multiple KILL objective conditions

### ISSUE THREAD

**Issue by Gholdin** [CathieNova/Haven-Tools-and-Helpers#9]
**Description**
When creating multiple KILL objective conditions selected for TARGET "scav", every condition after the first KILL objective does not populate with the appropriate SAVAGE ROLE selection window. See picture for reference.

**Steps to Reproduce**
1. Create more than 1 KILL objective condition.
2. Set the target to Scavs on (1+n) KILL conditions

**Expected Behavior**
The first set KILL objective set to TARGET "Scav" shows the appropriate SAVAGE ROLE window, as expected.

**Screenshots**
![Screenshot 2024-11-18 233335](https://github.com/user-attachments/assets/4455f56a-efa2-4758-8dc0-edc37c5f0d18)

**Browser**
Chrome

**Comment by CathieNova** [comment]
Fixed.

**Comment by Gholdin** [comment]
This issue has not been fixed

**Comment by Gholdin** [comment]
![Screenshot 2024-11-30 005112](https://github.com/user-attachments/assets/73700ce4-23f6-443c-b616-5b922960b5b3)
